//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nalichie
    {
        public int IdNalichie { get; set; }
        public int IdLekarstvo { get; set; }
        public int IdApteka { get; set; }
        public string Count { get; set; }
        public string Price { get; set; }
    
        public virtual Apteka Apteka { get; set; }
        public virtual Lekarstvo Lekarstvo { get; set; }
    }
}
